In [3]:
import numpy as np
import pandas as pd
import os
from matplotlib import pyplot as plt
import utilities as ut
from scipy.stats import normaltest
import datetime as dt
import seaborn as sns
import networkx as nx

In [ ]:
path_read = r'C:\Users\Javier\Documents\MEGA\Universitattt\Master\Thesis\Results\Probabilities'


In [1]:
dic_count = {'RUSSIA':'Government of the Russian Federation',
'AKT':'Oil Transporting Jt Stk Co Transneft',
'BKECON':'Vnesheconombank',
'BOM':'Bank of Moscow OJSC',
'CITMOS':'City Moscow',
'GAZPRU':'GAZPROM PJSC',
'GAZPRU.Gneft':'JSC Gazprom Neft',
'LUKOIL':'LUKOIL PJSC',
'MBT':'Mobile Telesystems',
'MDMOJC':'MDM Bank JSC',
'ALROSA':'ALROSA Company Ltd',
'ROSNEF':'Rosneftegaz OJSC',
'RSBZAO':'Jt Stk Co Russian Standard Bk',
'RUSAGB':'Joint-stock company Russian Agricultural Bank',
'RUSRAI':'JSC Russian Railways',
'SBERBANK':'Sberbank of Russia',
'VIP':'VimpelCom Ltd.',
'VTB':'VTB Bank (public joint-stock company)'}

In [2]:
for k,v in dic_count.items():
    print("'",end = '')
    print(v,end = "':'")
    print(k,end="',")

'Government of the Russian Federation':'RUSSIA','Oil Transporting Jt Stk Co Transneft':'AKT','Vnesheconombank':'BKECON','Bank of Moscow OJSC':'BOM','City Moscow':'CITMOS','GAZPROM PJSC':'GAZPRU','JSC Gazprom Neft':'GAZPRU.Gneft','LUKOIL PJSC':'LUKOIL','Mobile Telesystems':'MBT','MDM Bank JSC':'MDMOJC','ALROSA Company Ltd':'ALROSA','Rosneftegaz OJSC':'ROSNEF','Jt Stk Co Russian Standard Bk':'RSBZAO','Joint-stock company Russian Agricultural Bank':'RUSAGB','JSC Russian Railways':'RUSRAI','Sberbank of Russia':'SBERBANK','VimpelCom Ltd.':'VIP','VTB Bank (public joint-stock company)':'VTB',

In [14]:
dic = {'Government of the Russian Federation':'RUSSIA','Oil Transporting Jt Stk Co Transneft':'AKT',
    'Vnesheconombank':'BKECON','Bank of Moscow OJSC':'BOM','City Moscow':'CITMOS','GAZPROM PJSC':'GAZPRU',
    'JSC Gazprom Neft':'GAZPRU.Gneft','LUKOIL PJSC':'LUKOIL','Mobile Telesystems':'MBT',
    'MDM Bank JSC':'MDMOJC','ALROSA Company Ltd':'ALROSA','Rosneftegaz OJSC':'ROSNEF',
    'Jt Stk Co Russian Standard Bk':'RSBZAO','Joint-stock company Russian Agricultural Bank':'RUSAGB',
    'JSC Russian Railways':'RUSRAI','Sberbank of Russia':'SBERBANK','VimpelCom Ltd.':'VIP','VTB Bank (public joint-stock company)':'VTB'}

In [7]:
path_countryrank = r'C:\Users\Javier\Documents\MEGA\Universitattt\Master\Thesis\CDS_data\factor_model\Ioannis'
port_a = pd.read_csv(os.path.join(path_countryrank, 'PortfolioA.csv'),index_col = 1)

In [15]:
for i in port_a.index:
    port_a.loc[i,'Ticker'] = dic[i]

In [19]:
port_a = port_a[['Ticker','gamma']]

In [54]:
path = r'C:\Users\Javier\Documents\MEGA\Universitattt\Master\Thesis\CDS_data\factor_model\compare_period'
for folder in os.listdir(path):
    aux = port_a[['Ticker','gamma']]
    for file in [f for f in os.listdir(os.path.join(path,folder)) if f.startswith('portfolio')]:
        df = pd.read_csv(os.path.join(path,folder,file),index_col = 0)
        print(file)
        num = [s for s in file.replace('.csv','').split('_') if s.isdigit()]
        df.rename(columns = {'gamma':'gamma '+str(num[1])+' days'}, inplace = True)
        aux = pd.concat([aux, df['gamma '+str(num[1])+' days']], axis = 1)
    aux.sort_values(by = 'gamma', ascending = False, inplace = True)
    aux.loc['Mean','Ticker'] = '-'
    aux.iloc[-1,1:] = np.mean(aux)
    aux.to_csv(os.path.join(path,folder, 'comparisons_'+str(num[0]+'.csv')))

portfolio_10_delay_1.csv
portfolio_10_delay_2.csv
portfolio_10_delay_3.csv
portfolio_10_delay_1_5.csv
portfolio_10_delay_2_5.csv
portfolio_10_delay_3_5.csv
portfolio_15_delay_1.csv
portfolio_15_delay_2.csv
portfolio_15_delay_3.csv
portfolio_15_delay_1_5.csv
portfolio_15_delay_2_5.csv
portfolio_15_delay_3_5.csv
portfolio_20_delay_1.csv
portfolio_20_delay_2.csv
portfolio_20_delay_3.csv
portfolio_20_delay_1_5.csv
portfolio_20_delay_2_5.csv
portfolio_20_delay_3_5.csv


c:\users\javier\anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning:

Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False




In [46]:
aux.sort_values(by = 'gamma', ascending = False, inplace = True)

In [48]:
aux.loc['Mean','Ticker'] = '_'

In [51]:
aux.iloc[-1,1:] = np.mean(aux)

In [52]:
aux

Ticker     gamma  \
Government of the Russian Federation                 RUSSIA  1.000000   
GAZPROM PJSC                                         GAZPRU  0.750000   
Joint-stock company Russian Agricultural Bank        RUSAGB  0.750000   
Bank of Moscow OJSC                                     BOM  0.750000   
Sberbank of Russia                                 SBERBANK  0.708333   
VTB Bank (public joint-stock company)                   VTB  0.666667   
JSC Gazprom Neft                               GAZPRU.Gneft  0.625000   
JSC Russian Railways                                 RUSRAI  0.583333   
Rosneftegaz OJSC                                     ROSNEF  0.583333   
ALROSA Company Ltd                                   ALROSA  0.541667   
Oil Transporting Jt Stk Co Transneft                    AKT  0.541667   
LUKOIL PJSC                                          LUKOIL  0.541667   
City Moscow                                          CITMOS  0.541667   
Vnesheconombank                                      BKECON  0.541667   
MDM Bank JSC                                         MDMOJC  0.500000   
Jt Stk Co Russian Standard Bk                        RSBZAO  0.500000   
Mobile Telesystems                                      MBT  0.458333   
VimpelCom Ltd.                                          VIP  0.416667   
Mean                                                      _  0.611111   

                                                gamma 1   gamma 2   gamma 3  
Government of the Russian Federation           1.000000  1.000000  1.000000  
GAZPROM PJSC                                   0.556979  0.607790  0.634570  
Joint-stock company Russian Agricultural Bank  0.286148  0.389326  0.426433  
Bank of Moscow OJSC                            0.117074  0.174311  0.391760  
Sberbank of Russia                             0.120606  0.351299  0.478377  
VTB Bank (public joint-stock company)          0.147343  0.299534  0.273384  
JSC Gazprom Neft                               0.607227  0.501897  0.568828  
JSC Russian Railways                           0.423341  0.565287  0.436614  
Rosneftegaz OJSC                               0.283983  0.469213  0.542764  
ALROSA Company Ltd                             0.098709  0.134212  0.160255  
Oil Transporting Jt Stk Co Transneft           0.405280  0.388298  0.600489  
LUKOIL PJSC                                    0.124253  0.249785  0.370079  
City Moscow                                    0.282443  0.203129  0.266454  
Vnesheconombank                                0.206722  0.308681  0.519191  
MDM Bank JSC                                   0.102480  0.111996  0.131893  
Jt Stk Co Russian Standard Bk                  0.124083  0.192021  0.251843  
Mobile Telesystems                             0.065479  0.100316  0.188711  
VimpelCom Ltd.                                 0.109363  0.183521  0.210738  
Mean                                           0.281195  0.346145  0.414021

In [60]:
df = pd.read_csv(r'C:\Users\Javier\Documents\MEGA\Universitattt\Master\Thesis\Results\Capital_periods\comp.csv', index_col = 0)

In [61]:
for i in df.index:
    u = df.loc[i,:].values
    print(u)

[1115153.28008921 1443009.11122655 2276912.39129326 3420615.94694032]
[1162329.05787076 1696356.83569126 3051125.05802187 4446963.10904212]
[1172175.77787155 1772004.83569732 3389979.44738427 4968393.28039747]
[1219351.5556531  1935971.77793266 3749041.72474437 5150985.72485652]
[1115153.28008921 1443579.05789326 2276912.39129326 3408023.05805042]
[1162329.05787076 1683194.00013466 3003379.3335736  4446958.39146687]
[1162329.05787076 1771434.8890306  3379550.83582592 4775388.88684618]
[1190879.3334286  1841620.22236955 3524814.22250421 5015569.05817902]
[1115153.28008921 1443579.05789326 2292869.77796121 3553286.71934545]
[1162329.05787076 1683194.00013466 3003949.28024032 4493564.27957634]
[1219351.5556531  1813069.94681171 3408035.65094137 4968393.28039747]
[1232514.39120971 1935971.77793266 3707976.61362997 5056634.16929342]


In [63]:
for time in [10,15,20]:
    print([i for i in df.index if str(time) in i])

['10', '10_1', '10_2', '10_3']
['15', '15_1', '15_2', '15_3']
['20', '20_1', '20_2', '20_3']
